-- Databases
CREATE DATABASE IF NOT EXISTS ECOMMERCE_BRONZE_DB;
CREATE DATABASE IF NOT EXISTS ECOMMERCE_SILVER_DB;
CREATE DATABASE IF NOT EXISTS ECOMMERCE_GOLD_DB;

-- Schemas
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_BRONZE_DB.OLIST;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_BRONZE_DB.FRANKFURTER;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_SILVER_DB.COMMERCE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_SILVER_DB.FINANCE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_GOLD_DB.SALES;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_GOLD_DB.PRODUCT;

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_INGEST_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Used for Snowpipe and COPY INTO loading';

CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_TRANSFORM_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Used for dbt transformations';

CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_ANALYTICS_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Used for querying Gold layer';