
  -- Create roles
CREATE ROLE IF NOT EXISTS ECOMMERCE_ENGINEER;
CREATE ROLE IF NOT EXISTS ECOMMERCE_DBT_RUNNER;
CREATE ROLE IF NOT EXISTS ECOMMERCE_ANALYST;

-- Engineer: full access to everything
GRANT ALL ON DATABASE ECOMMERCE_BRONZE_DB TO ROLE ECOMMERCE_ENGINEER;
GRANT ALL ON DATABASE ECOMMERCE_SILVER_DB TO ROLE ECOMMERCE_ENGINEER;
GRANT ALL ON DATABASE ECOMMERCE_GOLD_DB TO ROLE ECOMMERCE_ENGINEER;
GRANT ALL ON WAREHOUSE ECOMMERCE_INGEST_WH TO ROLE ECOMMERCE_ENGINEER;
GRANT ALL ON WAREHOUSE ECOMMERCE_TRANSFORM_WH TO ROLE ECOMMERCE_ENGINEER;
GRANT ALL ON WAREHOUSE ECOMMERCE_ANALYTICS_WH TO ROLE ECOMMERCE_ENGINEER;

-- dbt runner: read bronze, write silver and gold
GRANT USAGE ON DATABASE ECOMMERCE_BRONZE_DB TO ROLE ECOMMERCE_DBT_RUNNER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_BRONZE_DB TO ROLE ECOMMERCE_DBT_RUNNER;
GRANT SELECT ON ALL TABLES IN DATABASE ECOMMERCE_BRONZE_DB TO ROLE ECOMMERCE_DBT_RUNNER;
GRANT ALL ON DATABASE ECOMMERCE_SILVER_DB TO ROLE ECOMMERCE_DBT_RUNNER;
GRANT ALL ON DATABASE ECOMMERCE_GOLD_DB TO ROLE ECOMMERCE_DBT_RUNNER;
GRANT USAGE ON WAREHOUSE ECOMMERCE_TRANSFORM_WH TO ROLE ECOMMERCE_DBT_RUNNER;

-- Analyst: read gold only
GRANT USAGE ON DATABASE ECOMMERCE_GOLD_DB TO ROLE ECOMMERCE_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_GOLD_DB TO ROLE ECOMMERCE_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE ECOMMERCE_GOLD_DB TO ROLE ECOMMERCE_ANALYST;
GRANT USAGE ON WAREHOUSE ECOMMERCE_ANALYTICS_WH TO ROLE ECOMMERCE_ANALYST;

-- Assign engineer role to user
GRANT ROLE ECOMMERCE_ENGINEER TO USER HARISNOWFLAKEACC;