
USE ROLE ACCOUNTADMIN;


CREATE SCHEMA IF NOT EXISTS ECOMMERCE_BRONZE_DB.FRANKFURTER;


GRANT USAGE ON SCHEMA ECOMMERCE_BRONZE_DB.FRANKFURTER TO ROLE ECOMMERCE_ENGINEER;
GRANT CREATE TABLE ON SCHEMA ECOMMERCE_BRONZE_DB.FRANKFURTER TO ROLE ECOMMERCE_ENGINEER;


USE ROLE ECOMMERCE_ENGINEER;
USE DATABASE ECOMMERCE_BRONZE_DB;

CREATE TABLE IF NOT EXISTS FRANKFURTER.EXCHANGE_RATES_RAW (
    rate_date       DATE,
    base_currency   VARCHAR(10),
    target_currency VARCHAR(10),
    rate            FLOAT,
    _loaded_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);